###
GET http://localhost:8080/api/token/none

###
GET http://localhost:8080/api/token/required

###
GET http://localhost:8080/api/token/required
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJib2JieSIsImlhdCI6MTY3NjgxMTExMSwiZXhwIjoxNjc2ODk3NTExfQ.Yt8eP2J86zZL_5Q9wJl94-wCPwI99a1cLduWOz6Cm5E

###
GET http://localhost:8080/api/token/optional

###
GET http://localhost:8080/api/token/optional
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJib2JieSIsImlhdCI6MTY3NjgxMTExMSwiZXhwIjoxNjc2ODk3NTExfQ.Yt8eP2J86zZL_5Q9wJl94-wCPwI99a1cLduWOz6Cm5E