management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#logging:
#  level:
#    org.springframework.cloud.sleuth: DEBUG

server:
  tomcat:
    mbeanregistry:
      enabled: true