version: '3.9'

services:
  storage:
    image: openzipkin/zipkin-mysql
    container_name: zipkin-mysql
    environment:
      - MYSQL_DATABASE=zipkin
      - MYSQL_USER=zipkin
      - MYSQL_PASSWORD=zipkin
    ports:
      - 13306:3306
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_DB=zipkin
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      - MYSQL_HOST=zipkin-mysql
      - MYSQL_TCP_PORT=3306
    ports:
      - 9411:9411
    depends_on:
      - storage
    restart: always

  dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: dependencies
    entrypoint: crond -f
    environment:
      - MYSQL_DB=zipkin
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      - MYSQL_HOST=zipkin-mysql
      - MYSQL_TCP_PORT=3306
    depends_on:
      - storage
    restart: always