server:
  port: 18080

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

tus:
  data:
    path: "video/tus"
    expiration: 60000
  save:
    path: "video"
  output:
    path:
      hls: "video/hls"
      mp4: "video/mp4"

ffmpeg:
  path: /usr/local/bin/ffmpeg
ffprobe:
  path: /usr/local/bin/ffprobe