server:
  port: 0

spring:
  application:
    name: api-service
  main:
    allow-bean-definition-overriding: true

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 3000

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

token: test-token

gateway.url: http://localhost:9000

logging:
  level:
    com.example.api.feign: DEBUG