spring:
  profiles:
    include: core
    active: local
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/test?useSSL=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO  #SQL ?? ??? Table? ??? ???.
      sqlonly: OFF     #SQL? ??? ???.
      sqltiming: INFO    #SQL? ????? ????.
      connection : OFF  # ??? ????